# Generated by Django 2.2.28 on 2022-09-27 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0025_auto_20220921_0928'),
        ('order', '0012_order_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineattribute',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_option_group', to='catalogue.ProductOptionGroup'),
        ),
        migrations.AddField(
            model_name='lineattribute',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
