# Generated by Django 2.2.28 on 2022-09-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20220927_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
