# Generated by Django 2.2.28 on 2022-10-21 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20220928_1332'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='shippingaddress',
    #         name='lat',
    #     ),
    #     migrations.RemoveField(
    #         model_name='shippingaddress',
    #         name='lng',
    #     ),
    # ]
